# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-24 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=300)),
                ('isbn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ISBN')),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.URLField(blank=True, null=True)),
                ('arquivo', models.URLField()),
                ('tipo_livro', models.CharField(choices=[('FISICO', 'FISICO'), ('EBOOK', 'EBOOK')], max_length=100, verbose_name='Tipo do Livro')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('titulo',),
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
